OANDA DOCUMENT: https://developer.oanda.com/rest-live-v20/instrument-df/

In [1]:
import requests
import defs
import pandas as pd

In [2]:
session = requests.Session()

we want to maintian "persistant connection" - using a session, to prevent creating a new request creating server

In [3]:
url = f"{defs.OANDA_URL}/accounts/{defs.ACCOUNT_ID}/instruments"

In [4]:
url

'https://api-fxpractice.oanda.com/v3/accounts/101-004-40673488-001/instruments'

In [5]:
response = session.get(url, params=None, headers=defs.SECURE_HEADER)

In [6]:
response.status_code

200

In [7]:
data = response.json()

In [8]:
data.keys()

dict_keys(['instruments', 'lastTransactionID'])

In [9]:
instruments = data['instruments']

In [10]:
instruments[0].keys()

dict_keys(['name', 'type', 'displayName', 'pipLocation', 'displayPrecision', 'tradeUnitsPrecision', 'minimumTradeSize', 'maximumTrailingStopDistance', 'minimumTrailingStopDistance', 'maximumPositionSize', 'maximumOrderUnits', 'marginRate', 'guaranteedStopLossOrderMode', 'tags', 'financing'])

In [11]:
instrument_data = []
for item in instruments:
    new_obj = dict(
        name = item["name"],
        type = item["type"],
        displayName = item["displayName"],
        pipLocation = item["pipLocation"],
        marginRate = item["marginRate"]
    )
    instrument_data.append(new_obj)

In [12]:
for item in instrument_data[0:3]:
    print(item)

{'name': 'TRY_JPY', 'type': 'CURRENCY', 'displayName': 'TRY/JPY', 'pipLocation': -2, 'marginRate': '0.25'}
{'name': 'CHF_JPY', 'type': 'CURRENCY', 'displayName': 'CHF/JPY', 'pipLocation': -2, 'marginRate': '0.03333333333333'}
{'name': 'NZD_SGD', 'type': 'CURRENCY', 'displayName': 'NZD/SGD', 'pipLocation': -4, 'marginRate': '0.05'}

In [13]:
instrument_df = pd.DataFrame.from_dict(instrument_data)

In [14]:
instrument_df

          name      type   displayName  pipLocation        marginRate
0      TRY_JPY  CURRENCY       TRY/JPY           -2              0.25
1      CHF_JPY  CURRENCY       CHF/JPY           -2  0.03333333333333
2      NZD_SGD  CURRENCY       NZD/SGD           -4              0.05
3      GBP_NZD  CURRENCY       GBP/NZD           -4              0.05
4      XAU_CHF     METAL      Gold/CHF           -2              0.05
..         ...       ...           ...          ...               ...
118    EUR_USD  CURRENCY       EUR/USD           -4  0.03333333333333
119   SG30_SGD       CFD  Singapore 30           -1              0.10
120    GBP_JPY  CURRENCY       GBP/JPY           -2  0.03333333333333
121    USD_TRY  CURRENCY       USD/TRY           -4              0.25
122  WHEAT_USD       CFD         Wheat           -2              0.10

[123 rows x 5 columns]

In [15]:
instrument_df.to_pickle("instruments.pkl")

In [16]:
new_table = pd.read_pickle("instruments.pkl")

In [17]:
new_table

          name      type   displayName  pipLocation        marginRate
0      TRY_JPY  CURRENCY       TRY/JPY           -2              0.25
1      CHF_JPY  CURRENCY       CHF/JPY           -2  0.03333333333333
2      NZD_SGD  CURRENCY       NZD/SGD           -4              0.05
3      GBP_NZD  CURRENCY       GBP/NZD           -4              0.05
4      XAU_CHF     METAL      Gold/CHF           -2              0.05
..         ...       ...           ...          ...               ...
118    EUR_USD  CURRENCY       EUR/USD           -4  0.03333333333333
119   SG30_SGD       CFD  Singapore 30           -1              0.10
120    GBP_JPY  CURRENCY       GBP/JPY           -2  0.03333333333333
121    USD_TRY  CURRENCY       USD/TRY           -4              0.25
122  WHEAT_USD       CFD         Wheat           -2              0.10

[123 rows x 5 columns]